AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EC2 and pull Docker image from ECR

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and Flask app
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  ECRRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  ECRInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ECRRole

  MonitorEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: moniter-key
      ImageId: ami-0f5ee92e2d63afc18
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      IamInstanceProfile: !Ref ECRInstanceProfile

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install docker -y
          service docker start

          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS \
          --password-stdin 208194581278.dkr.ecr.ap-south-1.amazonaws.com

          docker pull 208194581278.dkr.ecr.ap-south-1.amazonaws.com/monitor-app

          docker run -d -p 5000:5000 \
          208194581278.dkr.ecr.ap-south-1.amazonaws.com/monitor-app

Outputs:

  InstancePublicIP:
    Value: !GetAtt MonitorEC2.PublicIp